In [1]:
from __future__ import print_function #python2 와 python3 문법 동시사용
import torch

In [4]:
x=torch.empty(5,3) #초기화되지 않은 5x3 tensor
print(x)

tensor([[3.4066e+00, 4.7378e-23, 2.1164e-37],
        [8.3435e-10, 1.8963e-22, 5.0848e-14],
        [2.1765e-04, 1.4313e+01, 1.7136e-37],
        [3.5822e+00, 1.4787e-38, 5.7316e+01],
        [1.4787e-38, 1.6770e-37, 6.6016e-01]])


In [15]:
x=torch.rand(5,3) #무작위로 초기화된 tensor
print(x)

tensor([[0.8871, 0.6468, 0.9313],
        [0.0776, 0.9535, 0.4822],
        [0.6534, 0.7784, 0.1710],
        [0.4678, 0.4291, 0.7067],
        [0.2769, 0.5421, 0.1170]])


In [8]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


#### 기존 tensor를 바탕으로 새로운 tensor 만든다.
#### 메소드는 새로운 값을 제공받지 않는 한, 입력 tensor의 속성(ex.dtype)을 재사용

In [19]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [20]:
x=x.new_zeros(5,3,dtype=torch.double) #new_* 메소드는 크기를 받음
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [23]:
x=torch.randn_like(x,dtype=torch.float) #dtype을 override.결과는 동일한 크기를 가짐
print(x) #rand 함수, x와 같은 크기인 5x3 tensor

tensor([[ 1.2308, -1.0280, -0.3057],
        [-0.9085, -0.1412, -0.5476],
        [-0.2384,  1.8177,  1.6510],
        [ 0.5629, -0.5631, -0.2845],
        [-1.4446,  1.2391, -0.2116]])


In [24]:
print(x.size())

torch.Size([5, 3])


In [25]:
##연산
y=torch.rand(5,3) #덧셈
print(x+y)

tensor([[ 2.1062, -0.1441,  0.4262],
        [-0.3681,  0.3670, -0.3584],
        [-0.0240,  2.6660,  1.7189],
        [ 0.8469,  0.1679, -0.2442],
        [-1.1074,  1.5303,  0.3325]])


In [26]:
print(torch.add(x,y))

tensor([[ 2.1062, -0.1441,  0.4262],
        [-0.3681,  0.3670, -0.3584],
        [-0.0240,  2.6660,  1.7189],
        [ 0.8469,  0.1679, -0.2442],
        [-1.1074,  1.5303,  0.3325]])


In [27]:
result=torch.empty(5,3)
torch.add(x,y,out=result) #덧셈 결과tensor를 인자로 제공. 출력값을 result에 넣음
print(result)

tensor([[ 2.1062, -0.1441,  0.4262],
        [-0.3681,  0.3670, -0.3584],
        [-0.0240,  2.6660,  1.7189],
        [ 0.8469,  0.1679, -0.2442],
        [-1.1074,  1.5303,  0.3325]])


#### y에 x더하기(바꿔치기 방식) 바꿔치기 연산뒤에는 _

In [28]:
y.add_(x)
print(y)

tensor([[ 2.1062, -0.1441,  0.4262],
        [-0.3681,  0.3670, -0.3584],
        [-0.0240,  2.6660,  1.7189],
        [ 0.8469,  0.1679, -0.2442],
        [-1.1074,  1.5303,  0.3325]])


In [29]:
x.copy_(y)
print(x)

tensor([[ 2.1062, -0.1441,  0.4262],
        [-0.3681,  0.3670, -0.3584],
        [-0.0240,  2.6660,  1.7189],
        [ 0.8469,  0.1679, -0.2442],
        [-1.1074,  1.5303,  0.3325]])


In [30]:
print(x[:,1])

tensor([-0.1441,  0.3670,  2.6660,  0.1679,  1.5303])


#### 크기변경 : tensor의 크기나 모양 변경 시 torch.view

In [31]:
x=torch.randn(4,4)#rand:정수, randi:실수, randn:정규분포, randperm:1dptj n까지 범위
y=x.view(16)
z=x.view(-1,8) #-1은 다른 차원이 정해지면 자동으로 계산되어 정해짐
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### tensor에 하나의 값만 존재한다면, .item()을 사용하면 숫자값을 얻을 수 있음

In [32]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.3713])
-0.37125909328460693


In [33]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


#### torch tensor를 numpy배열로 변환하기

In [34]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [35]:
a.add_(1) #하나를 변경하면 다른 하나도 변경됨
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### numpy배열을 torch tensor로 변환하기

In [36]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
