## autograd

In [1]:
import torch

In [2]:
x=torch.ones(2,2,requires_grad=True) 
#requires_grad=True 시 그 tensor에서 이뤄진 모든 연산을 추적
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn) #y는 연산의 결과로 생성된 것이므로 grad_fn을 가짐

In [5]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad) #입력값이 지정되지 않으면 기본값은 false
a.requires_grad_(True) #기존 tensor의 requires_grad 값을 바꿔치기
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)
print(a)
print(b)

False
True
tensor([[16.1295,  1.0175],
        [ 2.1009, -2.7706]], requires_grad=True)
tensor(273.2868, grad_fn=<SumBackward0>)


### gradient
#### backprop

In [9]:
out.backward() 
#out은 하나의 스칼라 값을 갖고 있기 때문에, out.backward(torch.tensor(1.)) 과 동일
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
x=torch.randn(3,requires_grad=True) #requires_grad=True는 backprop을 위한 준비

y=x*2
print(y)
print(y.data)
print(y.data.norm()) #모든 요소를 제곱 한 다음 합산, 마지막에 제곱근
while y.data.norm()<1000:  #.data.norm() 는 L2 distance
    y=y*2
    
print(y)

tensor([-2.2102, -0.6102, -4.2189], grad_fn=<MulBackward0>)
tensor([-2.2102, -0.6102, -4.2189])
tensor(4.8018)
tensor([ -565.8182,  -156.2236, -1080.0492], grad_fn=<MulBackward0>)


In [16]:
#torch.autograd 는 벡터-jacobian 곱을 계산하는 엔진 (?)
v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float) #클래스 score 변수
y.backward(v) # v 클래스 score에 대한 backprop 진행
print(x.grad) #dv/dx 변화도 추적

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [19]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():  
    # with torch.no_grad(): 로 코드 블럭을 감싸서 autograd가 .requires_grad=True
    # 인 tensor들의 연산 기록을 추적하는 것을 멈출 수 있음
    print((x**2).requires_grad)

True
True
False


In [20]:
print(x.requires_grad)
y=x.detach() #.detach() 를 호출해 content는 같지만 requires_grad가 다른 새로운tensor
print(y.requires_grad)
print(x.eq(y).all()) #데이터가 일치하는가?

True
False
tensor(True)
